FROM node:lts as build
WORKDIR /private/build

ARG FORMSPREE_DEPLOY_KEY
ARG FORMSPREE_PROJECT_ID
ARG GOOGLE_TAG_MANAGER_ID
ARG GOOGLE_TAG_MANAGER_ENVIRONMENT_AUTH_STRING
ARG GOOGLE_TAG_MANAGER_ENVIRONMENT_PREVIEW_NAME

ENV FORMSPREE_DEPLOY_KEY $FORMSPREE_DEPLOY_KEY
ENV FORMSPREE_PROJECT_ID $FORMSPREE_PROJECT_ID
ENV GOOGLE_TAG_MANAGER_ID $GOOGLE_TAG_MANAGER_ID
ENV GOOGLE_TAG_MANAGER_ENVIRONMENT_AUTH_STRING $GOOGLE_TAG_MANAGER_ENVIRONMENT_AUTH_STRING
ENV GOOGLE_TAG_MANAGER_ENVIRONMENT_PREVIEW_NAME $GOOGLE_TAG_MANAGER_ENVIRONMENT_PREVIEW_NAME

COPY package.json .
RUN npm install
COPY . .
RUN ["npm", "run", "build-and-deploy"]

FROM nginx
COPY --from=build /private/build/public /usr/share/nginx/html
EXPOSE 80
